// front/src/domain/AddCourseScreen.tsx
import Select from 'react-select'
import { Container } from "../base_components/Container/Container";
import { InputField } from "../base_components/InputField/InputField";
import { Toolbar } from "../base_components/Toolbar/Toolbar";
import { SaveButton } from '../base_components/Buttons/CrudButtons/SaveButton/SaveButton';
import { CloseButton } from '../base_components/Buttons/CrudButtons/CloseButton/CloseButton';
import { ADMINISTRATOR, COURESE_AND_MODULES } from './App/App';
import { useState } from 'react';
import { CreateCourseDto } from '../apis/api/course/CreateCourseDto';
import { useApis } from '../apis/ApiBase/ApiProvider';

export function AddCourseScreen() {
    const [name, setName] = useState("")
    const [department, setDepartment] = useState("")
    const [teacher, setTeacher] = useState("")
    const [credits, setCredits] = useState(0)
    const [controlType, setControlType] = useState("Test")
    const [description, setDescription] = useState("")

    const api = useApis()

    const createCourse = () => {
        const request: CreateCourseDto = {
            moduleId: localStorage.getItem("EducationalModuleId")!,
            name: name,
            credits: credits,
            controlType: controlType,
            department: department,
            teacher: teacher,
            description: description
        }
        api.specialCoursesApi.createCourse(request);
    }

    const renderOptions = () => {
        return [{ label: "Зачет", value: "Test" }, { label: "Экзамен", value: "Exam" }]
    }

    return (
        <Container>
            <Toolbar title="Добавить курс">
                <SaveButton to={ADMINISTRATOR + COURESE_AND_MODULES} onClick={createCourse}/>
                <CloseButton />
            </Toolbar>
            <InputField isRequired onChange={(e) => setName(e.target.value)}>
                Назавние курса
            </InputField>
            <InputField isRequired onChange={(e) => setDepartment(e.target.value)}>
                Назавние кафедры
            </InputField>
            <InputField isRequired onChange={(e) => setTeacher(e.target.value)}>
                Преподаватель
            </InputField>
            <InputField type={"number"} isRequired onChange={(e) => setCredits(parseInt(e.target.value))}>
                Количество зачетных единиц
            </InputField>
            <Select options={renderOptions()} defaultValue={renderOptions()[0]} onChange={(e) => setControlType(e?.value!)}/>
            <InputField isRequired onChange={(e) => setDescription(e.target.value)}>
                Описание курса
            </InputField>
        </Container>
    )
}

// core-front/src/app/components/screens/add-course-screen/add-course-screen.component.ts
import { Component } from '@angular/core';
import { TitleComponent } from '../../base_components/title/title.component';
import { ToolbarComponent } from '../../base_components/toolbar/toolbar.component';
import { TextFieldComponent } from '../../base_components/text-field/text-field.component';
import { FormsModule } from '@angular/forms';
import { SaveButtonComponent } from '../../base_components/save-button/save-button.component';
import { CloseButtonComponent } from '../../base_components/close-button/close-button.component';
import { CourceService } from '../../../services/course/cource.service';
import { CreateCourseDto } from '../../../services/course/dtos';
import { Callback } from '../../../services/callback';
import { Location } from '@angular/common';
import { NotificationService } from '../../../services/notification/notification.service';

@Component({
    selector: 'app-add-course-screen',
    standalone: true,
    imports: [TitleComponent, ToolbarComponent, TextFieldComponent, FormsModule, SaveButtonComponent, CloseButtonComponent],
    templateUrl: './add-course-screen.component.html',
    styleUrl: './add-course-screen.component.css'
})
export class AddCourseScreenComponent {
    moduleId: string = ""
    name: string = ""
    department: string = ""
    teacher: string = ""
    credits: number = 0
    contorlType: string = "Test"
    description: string = ""

    constructor(
        private courseService: CourceService, 
        private location: Location, 
        private notificationService: NotificationService
    ) {
        this.moduleId = sessionStorage.getItem('moduleId') || ""
    }

    setName(name: string) {
        this.name = name
    }

    setDepartment(department: string) {
        this.department = department
    }

    setTeacher(teacher: string) {
        this.teacher = teacher
    }

    setCredits(credits: string) {
        this.credits = parseInt(credits)
    }

    setContorlType(contorlType: string) {
        this.contorlType = contorlType
    }

    setDescription(description: string) {
        this.description = description
    }

    onSave() {
        let request = new CreateCourseDto(
            this.moduleId, 
            this.name, 
            this.credits, 
            this.contorlType, 
            this.department, 
            this.teacher, 
            this.description
        );
        let callback = new Callback(
            () => {
                console.log("Done")
                this.location.back()
                this.notificationService.info("Создание курса", "Курс создан")
            }, 
            (_: any) => this.notificationService.error("Создание курса", "Произошла ошибка"));
        this.courseService.createCourse(callback, request);
    }
}
<app-toolbar title="Добавить курс">
    <app-save-button (clickEvent)="onSave()"/>
    <app-close-button />
</app-toolbar>
<app-text-field title="Название курса" (fieldValue)="setName($event)"/>
<app-text-field title="Название кафедры" (fieldValue)="setDepartment($event)"/>
<app-text-field title="Преподаватель" (fieldValue)="setTeacher($event)"/>
<app-text-field title="Количество зачетных единиц" (fieldValue)="setCredits($event)"/>
<select [(ngModel)]="contorlType">
    <option value="Test">Зачет</option>
    <option value="Exam">Экзамен</option>
</select>
<app-text-field title="Описание курса" (fieldValue)="setDescription($event)"/>
