// core-front/src/app/components/action-bar/action-bar.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-action-bar',
    standalone: true,
    imports: [
        RouterLink
    ],
    templateUrl: './action-bar.component.html',
    styleUrl: './action-bar.component.css'
})
export class ActionBarComponent {
    items: ActionBarItem[] = [
        new ActionBarItem("Образовательные программы", "/administrator/educational_program"),
        new ActionBarItem("Курсы и модули", "/administrator/link2"),
        new ActionBarItem("Статистика", "/administrator/link3")
    ]
}

export class ActionBarItem {
    title: string;
    link: string;

    constructor(title: string, link: string) { 
        this.title = title;
        this.link = link;
    }
}

<header class="header">
    <div class="header_container">
        <div class="header_left">
            <a id="img_container" href="https://urfu.ru/">
                <img id="image_link_container" src="logo_urfu.svg" alt="Ufru logo" />
            </a>
            <nav>
                @for (item of items; track $index;) {
                    <a class="link" href={{item.link}}>{{item.title}}</a>
                }
            </nav>
        </div>
        <div class="header_right">
            <button class="search_button">
                <img src="/search_icon.svg" alt="Search icon" />
            </button>
        </div>
    </div>
</header>

// front/src/base_components/ActionBar/ActionBar.tsx
import { Link, Outlet } from "react-router-dom";
import styles from "./ActionBar.module.css"

interface Props {}

export function ActionBar(props: Props) {
    return (
        <>
            <header className={styles.header}>
                <div className={styles.header_container}>
                    <div className={styles.header_left}>
                        <a id={styles.img_container} href="https://urfu.ru/">
                            <img id={styles.image_link_container} src={process.env.PUBLIC_URL + "/logo_urfu.svg"} alt="Ufru logo" />
                        </a>
                        <nav>
                            <Link className={styles.link} to="/administrator/educational_program">Образовательные программы</Link>
                            <Link className={styles.link} to="/administrator/courses_and_modules">Курсы и модули</Link>
                            <Link className={styles.link} to="/administrator/statistics">Статистика</Link>
                        </nav>
                    </div>
                    <div className={styles.header_right}>
                        <button className={styles.search_button}>
                            <img src={process.env.PUBLIC_URL + "/search_icon.svg"} alt={"Search icon"} />
                        </button>
                    </div>
                </div>
            </header>

            <div>
                <Outlet />
            </div>
        </>
    )
}
