// core-front/src/app/components/add-group-screen/add-group-screen.component.ts
import { Component } from '@angular/core';
import { TitleComponent } from '../title/title.component';
import { TextFieldComponent } from '../text-field/text-field.component';
import { ToolbarComponent } from '../toolbar/toolbar.component';
import { SaveButtonComponent } from '../save-button/save-button.component';
import { CloseButtonComponent } from '../close-button/close-button.component';
import { ProgramService } from '../../services/program/program.service';
import {Location} from '@angular/common';
import { CreateGroupDTO } from '../../services/group/createGroup.dto';
import { GroupService } from '../../services/group/group.service';

@Component({
    selector: 'app-add-group-screen',
    standalone: true,
    imports: [TitleComponent, TextFieldComponent, ToolbarComponent, SaveButtonComponent, CloseButtonComponent],
    templateUrl: './add-group-screen.component.html',
    styleUrl: './add-group-screen.component.css'
})
export class AddGroupScreenComponent {
    id: string = localStorage.getItem('programId') || "";
    number: string = "";
    year: number = 0;

    constructor(private location: Location, private groupService: GroupService) { }

    setNumber(number: string) {
        this.number = number;
    }

    setYear(year: string) {
        this.year = parseInt(year);
    }

    onSave() {
        const request = new CreateGroupDTO(this.number, this.year, this.id);
        this.groupService.createGroup(request).subscribe(x => console.log(x));
        this.location.back()
    }
}

<app-toolbar title="Добавить академическую группу">
    <app-save-button (clickEvent)="onSave()"/>
    <app-close-button />
</app-toolbar>
<app-text-field title="Номер группы" (fieldValue)="setNumber($event)"/>
<app-text-field title="Год начала учебы (год, когда проходит первый семестр)" (fieldValue)="setYear($event)"/>

// front/src/domain/EducationalProgramScreen/AddGroupScreen/AddGroupScreen.tsx
import { useEffect, useState } from "react";
import { Container } from "../../../base_components/Container/Container";
import { CloseButton } from "../../../base_components/CrudButtons/CloseButton/CloseButton";
import { SaveButton } from "../../../base_components/CrudButtons/SaveButton/SaveButton";
import { Flex } from "../../../base_components/Flex/Flex";
import { Input } from "../../../base_components/Input/Input";
import { Toolbar } from "../../../base_components/Toolbar/Toolbar";
import { ADMINISTRATOR, EDUCATIONAL_PROGRAM } from "../../App/App";
import { useApis } from "../../../apis/ApiBase/ApiProvider";
import { CreateGroupDto } from "../../../apis/api/groups/CreateGroupDto";
import { PROGRAM_ID_KEY } from "../EducationalProgramDetailsScreen/EducationalProgramDetailsScreen";

export function AddGroupScreen() {
    const [groupNumber, setGroupNumber] = useState("");
    const [startYear, setStartYear] = useState(2023)
    const programId = localStorage.getItem(PROGRAM_ID_KEY);

    const api = useApis()

    const save = async () => {
        const group = {
            number: groupNumber,
            year: startYear,
            programId: programId
        } as CreateGroupDto
        await api.groupsApi.createGroup(group)
    }

    return (
        <Container>
            <Toolbar title="Добавить академическую группу">
                <SaveButton to={ADMINISTRATOR + EDUCATIONAL_PROGRAM + "/" + programId} onClick={() => {
                    console.log(ADMINISTRATOR + EDUCATIONAL_PROGRAM + "/" + programId);
                    console.log("ID: " + programId)
                    save()
                }
                } />
                <CloseButton to={ADMINISTRATOR + EDUCATIONAL_PROGRAM + "/" + programId} />
            </Toolbar>
            <Flex direction="column">
                <span>Номер группы</span>
                <Input type="text" placeholder="Text" onChange={(e) => {setGroupNumber(e.target.value)}} isRequired={false} />
                <span>Год начала учебы (год, когда проходит первый семестр)</span>
                <Input type="number" placeholder={"Год"} onChange={(e) => {setStartYear(e.target.valueAsNumber)}} isRequired={false} />
            </Flex>
        </Container>
    )
}
